# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface2(object):
    def setupUi(self, Interface2):
        Interface2.setObjectName("Interface2")
        Interface2.resize(772, 733)
        Interface2.setStyleSheet("background-image: url(:/images/111.jpeg);")
        self.centralwidget = QtWidgets.QWidget(Interface2)
        self.centralwidget.setObjectName("centralwidget")
        self.Process1 = QtWidgets.QPushButton(self.centralwidget)
        self.Process1.setGeometry(QtCore.QRect(50, 590, 191, 81))
        self.Process1.setStyleSheet("border-image: url(:/images/PROCESS 1.png);")
        self.Process1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/process1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Process1.setIcon(icon)
        self.Process1.setIconSize(QtCore.QSize(200, 110))
        self.Process1.setObjectName("Process1")
        self.Process2 = QtWidgets.QPushButton(self.centralwidget)
        self.Process2.setGeometry(QtCore.QRect(290, 590, 191, 81))
        self.Process2.setStyleSheet("border-image: url(:/images/PROCESS 2.png);")
        self.Process2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/process2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Process2.setIcon(icon1)
        self.Process2.setIconSize(QtCore.QSize(175, 125))
        self.Process2.setObjectName("Process2")
        self.Process3 = QtWidgets.QPushButton(self.centralwidget)
        self.Process3.setGeometry(QtCore.QRect(530, 590, 191, 81))
        self.Process3.setStyleSheet("border-image: url(:/images/PROCESS 3.png);")
        self.Process3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/process3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Process3.setIcon(icon2)
        self.Process3.setIconSize(QtCore.QSize(200, 100))
        self.Process3.setObjectName("Process3")
        self.Image = QtWidgets.QLabel(self.centralwidget)
        self.Image.setGeometry(QtCore.QRect(50, 120, 651, 411))
        self.Image.setText("")
        self.Image.setPixmap(QtGui.QPixmap("car.jpg"))
        self.Image.setScaledContents(True)
        self.Image.setObjectName("Image")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 351, 81))
        self.label.setStyleSheet("\n"
"border-image: url(:/images/downloa1d.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        Interface2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Interface2)
        self.statusbar.setObjectName("statusbar")
        Interface2.setStatusBar(self.statusbar)

        self.retranslateUi(Interface2)
        QtCore.QMetaObject.connectSlotsByName(Interface2)

    def retranslateUi(self, Interface2):
        _translate = QtCore.QCoreApplication.translate
        Interface2.setWindowTitle(_translate("Interface2", "MainWindow"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interface2 = QtWidgets.QMainWindow()
    ui = Ui_Interface2()
    ui.setupUi(Interface2)
    Interface2.show()
    sys.exit(app.exec_())
