# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface3(object):
    def setupUi(self, interface3):
        interface3.setObjectName("interface3")
        interface3.resize(772, 733)
        interface3.setStyleSheet("background-image: url(:/images/111.jpeg);")
        self.centralwidget = QtWidgets.QWidget(interface3)
        self.centralwidget.setObjectName("centralwidget")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(50, 540, 91, 81))
        self.Button1.setStyleSheet("border-image: url(:/images/ocr.png);")
        self.Button1.setText("")
        self.Button1.setObjectName("Button1")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(250, 20, 281, 81))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("border-image: url(:/images/downloa1d.png);")
        self.label1.setText("")
        self.label1.setScaledContents(False)
        self.label1.setObjectName("label1")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(320, 460, 131, 81))
        self.Button2.setStyleSheet("border-image: url(:/images/back1.png);")
        self.Button2.setText("")
        self.Button2.setObjectName("Button2")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(580, 540, 141, 81))
        self.Button3.setStyleSheet("border-image: url(:/images/check.png);")
        self.Button3.setText("")
        self.Button3.setIconSize(QtCore.QSize(30, 30))
        self.Button3.setObjectName("Button3")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(60, 150, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setStyleSheet("border-image: url(:/images/numberplate.PNG);")
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(60, 290, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setStyleSheet("border-image: url(:/images/text.png);")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.number = QtWidgets.QLabel(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(410, 140, 321, 81))
        self.number.setText("")
        self.number.setPixmap(QtGui.QPixmap("numberplate.jpg"))
        self.number.setScaledContents(True)
        self.number.setObjectName("number")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(390, 280, 341, 71))
        self.textEdit.setStyleSheet("border-image: url(:/images/blank.jpg);")
        self.textEdit.setObjectName("textEdit")
        interface3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface3)
        self.statusbar.setObjectName("statusbar")
        interface3.setStatusBar(self.statusbar)

        self.retranslateUi(interface3)
        QtCore.QMetaObject.connectSlotsByName(interface3)

    def retranslateUi(self, interface3):
        _translate = QtCore.QCoreApplication.translate
        interface3.setWindowTitle(_translate("interface3", "MainWindow"))
        self.textEdit.setHtml(_translate("interface3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">DL 7CQ 3780</span></p></body></html>"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface3 = QtWidgets.QMainWindow()
    ui = Ui_interface3()
    ui.setupUi(interface3)
    interface3.show()
    sys.exit(app.exec_())
