# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface3(object):
    def setupUi(self, interface3):
        interface3.setObjectName("interface3")
        interface3.resize(772, 733)
        interface3.setStyleSheet("border-image: url(:/images/111.jpeg);")
        self.centralwidget = QtWidgets.QWidget(interface3)
        self.centralwidget.setObjectName("centralwidget")
        self.Sub = QtWidgets.QPushButton(self.centralwidget)
        self.Sub.setGeometry(QtCore.QRect(110, 550, 171, 71))
        self.Sub.setStyleSheet("\n"
"border-image: url(:/images/submit11.png);")
        self.Sub.setText("")
        self.Sub.setObjectName("Sub")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(240, 20, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("border-image: url(:/images/downloa1d.png);")
        self.label1.setText("")
        self.label1.setScaledContents(False)
        self.label1.setObjectName("label1")
        self.Check = QtWidgets.QPushButton(self.centralwidget)
        self.Check.setGeometry(QtCore.QRect(470, 550, 181, 61))
        self.Check.setStyleSheet("border-image: url(:/images/check1.jpg);")
        self.Check.setText("")
        self.Check.setObjectName("Check")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(60, 160, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label2.setFont(font)
        self.label2.setStyleSheet("border-image: url(:/images/OWNER NAME.PNG);")
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(60, 310, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label3.setFont(font)
        self.label3.setStyleSheet("border-image: url(:/images/text.png);")
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.TE2 = QtWidgets.QTextEdit(self.centralwidget)
        self.TE2.setEnabled(True)
        self.TE2.setGeometry(QtCore.QRect(450, 310, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TE2.setFont(font)
        self.TE2.setStyleSheet("border-image: url(:/images/blank.jpg);")
        self.TE2.setObjectName("TE2")
        self.TE1 = QtWidgets.QTextEdit(self.centralwidget)
        self.TE1.setEnabled(True)
        self.TE1.setGeometry(QtCore.QRect(450, 160, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.TE1.setFont(font)
        self.TE1.setStyleSheet("border-image: url(:/images/blank.jpg);")
        self.TE1.setObjectName("TE1")
        interface3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface3)
        self.statusbar.setObjectName("statusbar")
        interface3.setStatusBar(self.statusbar)

        self.retranslateUi(interface3)
        QtCore.QMetaObject.connectSlotsByName(interface3)

    def retranslateUi(self, interface3):
        _translate = QtCore.QCoreApplication.translate
        interface3.setWindowTitle(_translate("interface3", "MainWindow"))
        self.TE2.setHtml(_translate("interface3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">DL 7CQ 3780</span></p></body></html>"))
        self.TE1.setHtml(_translate("interface3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">XYZ</span></p></body></html>"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface3 = QtWidgets.QMainWindow()
    ui = Ui_interface3()
    ui.setupUi(interface3)
    interface3.show()
    sys.exit(app.exec_())
