# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '5.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_interface3(object):
    def setupUi(self, interface3):
        interface3.setObjectName("interface3")
        interface3.resize(772, 733)
        interface3.setStyleSheet("border-image: url(:/images/111.jpeg);")
        self.centralwidget = QtWidgets.QWidget(interface3)
        self.centralwidget.setObjectName("centralwidget")
        self.Sub = QtWidgets.QPushButton(self.centralwidget)
        self.Sub.setGeometry(QtCore.QRect(190, 270, 401, 321))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.Sub.setFont(font)
        self.Sub.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Sub.setAutoFillBackground(False)
        self.Sub.setStyleSheet("border-image: url(:/images/access granted.jpg);")
        self.Sub.setText("")
        self.Sub.setObjectName("Sub")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(230, 40, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setStyleSheet("border-image: url(:/images/downloa1d.png);")
        self.label1.setText("")
        self.label1.setScaledContents(False)
        self.label1.setObjectName("label1")
        interface3.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(interface3)
        self.statusbar.setObjectName("statusbar")
        interface3.setStatusBar(self.statusbar)

        self.retranslateUi(interface3)
        QtCore.QMetaObject.connectSlotsByName(interface3)

    def retranslateUi(self, interface3):
        _translate = QtCore.QCoreApplication.translate
        interface3.setWindowTitle(_translate("interface3", "MainWindow"))
import icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface3 = QtWidgets.QMainWindow()
    ui = Ui_interface3()
    ui.setupUi(interface3)
    interface3.show()
    sys.exit(app.exec_())
